name: 🔐 IMAP Server Connection Issue
description: Report issues related to IMAP server authentication, connection, or server-specific operations
title: "[IMAP issue]: "
labels: ["possible_bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## 🔐 Issue related to IMAP Server
        
        Thank you for reporting an issue! This template is for problems specifically related to:
        - IMAP server authentication failures
        - Connection issues with specific IMAP servers
        - Server-specific operation failures
        - SSL/TLS connection problems
        
        Please fill out the information below to help us diagnose the issue.

  - type: input
    id: community_node_version
    attributes:
      label: n8n-nodes-imap Version
      description: What version of n8n-nodes-imap are you using?
      placeholder: "e.g., 2.11.0"
    validations:
      required: true

  - type: dropdown
    id: imap_server
    attributes:
      label: IMAP Server Type
      description: Which IMAP server are you connecting to?
      options:
        - Gmail
        - Outlook/Hotmail (outlook.live.com)
        - Yahoo Mail
        - iCloud Mail
        - ProtonMail
        - Zoho Mail
        - FastMail
        - Custom/Corporate Exchange Server
        - Other (please specify in description)
    validations:
      required: true

  - type: textarea
    id: error_description
    attributes:
      label: Error Description
      description: Describe the issue you're experiencing
      placeholder: "e.g., Connection times out when trying to authenticate with Gmail using app password"
    validations:
      required: true

  - type: textarea
    id: error_message
    attributes:
      label: Error Message
      description: If you received an error message, please paste it here
      placeholder: "Paste the exact error message here"
      render: text
    validations:
      required: false

  - type: textarea
    id: n8n_logs
    attributes:
      label: N8N Logs
      description: |
        Please provide relevant n8n logs. To get logs:
        1. Set N8N_LOG_LEVEL=debug in your environment variables
        2. **Enable IMAP node debug mode**: Set N8N_NODES_DEBUG_ENABLED=true in your environment variables
        3. Reproduce the issue
        4. Check n8n logs in your console or log files
        5. Copy relevant log entries here
        
        **Note:** When N8N_NODES_DEBUG_ENABLED=true is set, the IMAP node will create a "debug" output with detailed logs and additional debug capabilities.
        
        **Important:** Remove any sensitive information like passwords, tokens, or personal data!
      placeholder: "Paste relevant log entries here (remove sensitive information)"
      render: text
    validations:
      required: false

  - type: textarea
    id: reproduction_steps
    attributes:
      label: Steps to Reproduce
      description: Please provide step-by-step instructions to reproduce the issue
      placeholder: |
        1. Set up IMAP credentials with...
        2. Create a workflow with...
        3. Execute the workflow...
        4. Error occurs...
    validations:
      required: false

  - type: input
    id: n8n_version
    attributes:
      label: N8N Version
      description: What version of n8n are you running?
      placeholder: "e.g., 1.65.1"
    validations:
      required: false

  - type: checkboxes
    id: troubleshooting
    attributes:
      label: Troubleshooting Checklist
      description: Please confirm you have tried these basic troubleshooting steps
      options:
        - label: I have verified my IMAP server settings are correct
        - label: I have tested the same credentials with another email client (Thunderbird, Outlook, etc.)
        - label: I have checked if my IMAP server requires app passwords or has 2FA enabled
        - label: I have reviewed the server's security settings and allowed "less secure apps" if needed
        - label: I have checked firewall and network connectivity to the IMAP server
        - label: I have enabled debug mode by setting N8N_NODES_DEBUG_ENABLED=true

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or information about the problem here
      placeholder: "Any additional information that might help..."
    validations:
      required: false