name: Release
on:
  workflow_run:
    workflows: ['Test']
    types:
      - completed
    branches:
      - master
  push:
    branches:
      - beta
  workflow_dispatch:

permissions:
  contents: read # for checkout

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'master'
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for trusted publishing and npm provenance
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: npm clean-install
      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: npm audit signatures
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
  release-beta:
    name: Publish Beta
    runs-on: ubuntu-latest
    if: (github.event_name == 'push' && github.ref == 'refs/heads/beta') || (github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/beta')
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for trusted publishing and npm provenance
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.sha }}
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: npm clean-install
      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: npm audit signatures
      - name: Build and test
        run: npm run prepublishOnly
      - name: Run Jest tests with coverage
        run: npx jest --coverage
      - name: Fetch master branch for beta diff
        run: git fetch origin master beta --tags
      - name: Set version env
        run: echo "NEXT_VERSION=$(git describe --tags --always --abbrev=7 | sed 's/^v//; s/$/-beta/')" >> $GITHUB_ENV
      - name: Set version
        run: npm version $NEXT_VERSION --no-git-tag-version --allow-same-version
      - name: Publish to npm
        env:
          BETA_BASE_REF: origin/master
          BETA_HEAD_REF: HEAD
          BETA_BUG_REPORT_URL: https://github.com/umanamente/n8n-nodes-imap/issues/new/choose
        run: npm run publish:beta:ci
